### ISSUE TITLE
Newsletter: Save Custom CSS for future posts

### ISSUE THREAD

**Issue by bsanevans** [Automattic/newspack-newsletters#480] opened 2021-05-21 07:07 UTC
**Is your feature request related to a problem? Please describe.**
At the moment, the Custom CSS added to Newsletter posts is only saved for that post.

**Describe the solution you'd like**
It would be nice if this was saved for future posts, too, so we don't have to add the same CSS each time.

**Additional context**
4005423-zd-woothemes

**Comment by laurelfulford** [comment] 2021-06-22 15:46
I would have expected the Custom CSS to be saved when added to a layout, but that doesn't seem to work for me. I'm not sure if that was a deliberate decision due to it being possible to break things with the Custom CSS (@thomasguillot?), if it's not working as expected, or if it hasn't been considered as a feature yet - just wanted to add a note in case it currently isn't working as expected!

**Comment by kendraschaefer** [comment] 2021-06-29 06:12
Same - I tried to create a newsletter layout using custom CSS, but all the custom CSS disappears when the layout is saved. Considering that I cannot input custom HTML blocks, this heavily limits the styling features.

**Comment by adekbadek** [comment] 2021-08-13 13:15
Closing as duplicate of #538.

**Closed by adekbadek** 2021-08-13 13:15 UTC
Labels: Feature Request
