### ISSUE TITLE
Save newsletter draft, pre-send, but can't edit that draft instance 

### ISSUE THREAD

**Issue by jsmall24** [Automattic/newspack-newsletters#494] opened 2021-07-08 14:52 UTC
Maybe this is as-designed, but when I start authoring a newsletter edition, I can grab a template and start filling it in with fresh content, and I can save as draft. However, save-as-draft seems to have no effect other than putting a newsletter draft in my Newsletters table. When I go to edit that draft, I am asked to select a template again, and none of the content I added or posts I selected in the draft are there.

This is a problem particularly for a team that wants to edit newsletter content collaboratively pre-send -- there's nothing to edit. The only workaround I have come up with is to save each draft as a new template so the next person can pull it in, make edits, then update template, until the last person who reviews/sends finally sends the edition out.

Screen shots show me picking a template for a new newsletter draft, then how that draft appears in the list when I save as draft. When I go back to it, I'm presented with the same pick-a-template UI. Doesn't matter if I pick a template or start from scratch, my edits on the draft are lost.

![Screen Shot 2021-07-08 at 9 07 00 AM](https://user-images.githubusercontent.com/67332810/124943192-ea7ab000-dfd1-11eb-8f83-c7b09b7cf5f2.png)
![Screen Shot 2021-07-08 at 9 10 48 AM](https://user-images.githubusercontent.com/67332810/124943273-f7979f00-dfd1-11eb-80ab-c8907c901a2f.png)

**Comment by jsmall24** [comment] 2021-07-20 14:29
So here's some new information that might help with this:

If I go to the Newsletters table in admin and select a draft, and choose to edit using Classic Editor, I can see my draft. But if I choose to edit using Block Editor, I still am taken through the steps I noted above, and don't get to see my draft content.

Even if I choose to edit using Classic Editor, and then once in the draft choose to switch to Block Editor, same thing -- I am then presented with the "choose a template" interface and, whether I pick one or choose Start from Scratch, never get to see my draft content.

**Comment by jsmall24** [comment] 2021-07-20 20:33
And, to be clear, saving as draft DOES create a draft in Mailchimp that can be edited in Mailchimp. But the point is that we do our editorial collaboration in the CMS and have a limit on the number of editing accounts we can have in Mailchimp -- so we would prefer to do all editing on our emails in WP/Newspack and send from there.

**Comment by miguelpeixe** [comment] 2021-08-20 19:46
Hi, @jsmall24!

I was not able to reproduce the problem you are experiencing. In the last month, the Mailchimp integration has undergone a few changes that might have fixed the issue.

In the case you are still having this problem, can you try creating a new draft using a different browser or incognito mode? The important thing I want to eliminate while investigating is a potential conflict with a browser extension.

**Comment by miguelpeixe** [comment] 2021-08-31 13:53
I'm closing this for now, we can reopen it if the problem resurfaces.

**Closed by miguelpeixe** 2021-08-31 13:53 UTC

**Comment by DennisNDean** [comment] 2023-07-15 19:41
Resurrecting this thread to say I'm currently debugging the same issue. It's only affecting one of our administrators, though. If I'm logged in as me, I can save and edit draft newsletters as expected, as can our other admins. If this particular admin tries, or if I'm logged in as him —so the issue is machine/browser independent — drafts can be created, and I see the changes being saved as revisions in the wp_posts table, but when you back out and try to open the draft for editing, it gives you the template select screen, and then that fresh template gets saved as a new revision.
