### ISSUE TITLE
Letterhead link HTML displays on Newspack plugin Engagement screen

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-newsletters#686] opened 2022-01-14 19:07 UTC
I'm not sure if this is a Newsletters bug per se, or a bug with how these labels are handled in the Newspack Plugin:

When you navigate to WP Admin > Newspack > Engagement, the label for the Letterhead API key shows HTML for a link back to their site. This link looks like it's coming from the Newsletters plugin [here](https://github.com/Automattic/newspack-newsletters/blob/3fc376a810d4292697f4682156cf6bedfd931f0b/includes/class-newspack-newsletters-settings.php#L107).

You can see the markup in the bottom screenshot here:

![image](https://user-images.githubusercontent.com/177561/149571313-e3ee71ef-5769-44bd-b022-a47eca18657d.png)

**Comment by miguelpeixe** [comment] 2022-01-14 19:16
It's a duplicate of #645 and is getting fixed by https://github.com/Automattic/newspack-plugin/pull/1432

**Comment by laurelfulford** [comment] 2022-01-14 21:16
🤦‍♀️ Thanks @miguelpeixe! I searched for "Letterhead" in both repos, but that didn't turn that one up! Closing this issue as a duplicate.

**Closed** 2022-01-14 21:16 UTC
Labels: bug
