### ISSUE TITLE
API Error: You cannot use this resource

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-newsletters#373] opened 2020-11-16 11:19 UTC
Some publishers are intermittently seeing this error message when updating newsletters:

> You cannot use this resource

<img width="842" alt="Screen Shot 2020-11-12 at 15 38 45" src="https://user-images.githubusercontent.com/136342/99246566-6a62c880-27fd-11eb-868b-8ca10048dba0.png">

I couldn't find information about that particular error from searching around so it's unclear where it's coming from but it's not in our codebase, so I suspect it's coming from the Mailchimp API.

It would be good to see if we can a) handle it better (e.g. automatic retries) or b) find the issue and feed back to Mailchimp.

**Comment by adekbadek** [comment] 2022-01-28 17:18
Cannot reproduce, might've been fixed in the meantime.

**Closed by adekbadek** 2022-01-28 17:18 UTC
Labels: bug
